# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daprclient.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
require 'google/protobuf/empty_pb'
require 'google/protobuf/duration_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("daprclient.proto", :syntax => :proto3) do
    add_message "daprclient.CloudEventEnvelope" do
      optional :id, :string, 1
      optional :source, :string, 2
      optional :type, :string, 3
      optional :specVersion, :string, 4
      optional :dataContentType, :string, 5
      optional :topic, :string, 6
      optional :data, :message, 7, "google.protobuf.Any"
    end
    add_message "daprclient.BindingEventEnvelope" do
      optional :name, :string, 1
      optional :data, :message, 2, "google.protobuf.Any"
      map :metadata, :string, :string, 3
    end
    add_message "daprclient.BindingResponseEnvelope" do
      optional :data, :message, 1, "google.protobuf.Any"
      repeated :to, :string, 2
      repeated :state, :message, 3, "daprclient.State"
      optional :concurrency, :string, 4
    end
    add_message "daprclient.InvokeEnvelope" do
      optional :method, :string, 1
      optional :data, :message, 2, "google.protobuf.Any"
      map :metadata, :string, :string, 3
    end
    add_message "daprclient.GetTopicSubscriptionsEnvelope" do
      repeated :topics, :string, 1
    end
    add_message "daprclient.GetBindingsSubscriptionsEnvelope" do
      repeated :bindings, :string, 1
    end
    add_message "daprclient.State" do
      optional :key, :string, 1
      optional :value, :message, 2, "google.protobuf.Any"
      optional :etag, :string, 3
      map :metadata, :string, :string, 4
      optional :options, :message, 5, "daprclient.StateOptions"
    end
    add_message "daprclient.StateOptions" do
      optional :concurrency, :string, 1
      optional :consistency, :string, 2
      optional :retryPolicy, :message, 3, "daprclient.RetryPolicy"
    end
    add_message "daprclient.RetryPolicy" do
      optional :threshold, :int32, 1
      optional :pattern, :string, 2
      optional :interval, :message, 3, "google.protobuf.Duration"
    end
  end
end

module Daprclient
  CloudEventEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("daprclient.CloudEventEnvelope").msgclass
  BindingEventEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("daprclient.BindingEventEnvelope").msgclass
  BindingResponseEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("daprclient.BindingResponseEnvelope").msgclass
  InvokeEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("daprclient.InvokeEnvelope").msgclass
  GetTopicSubscriptionsEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("daprclient.GetTopicSubscriptionsEnvelope").msgclass
  GetBindingsSubscriptionsEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("daprclient.GetBindingsSubscriptionsEnvelope").msgclass
  State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("daprclient.State").msgclass
  StateOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("daprclient.StateOptions").msgclass
  RetryPolicy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("daprclient.RetryPolicy").msgclass
end
