# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dapr.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
require 'google/protobuf/empty_pb'
require 'google/protobuf/duration_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("dapr.proto", :syntax => :proto3) do
    add_message "dapr.InvokeServiceResponseEnvelope" do
      optional :data, :message, 1, "google.protobuf.Any"
      map :metadata, :string, :string, 2
    end
    add_message "dapr.DeleteStateEnvelope" do
      optional :storeName, :string, 1
      optional :key, :string, 2
      optional :etag, :string, 3
      optional :options, :message, 4, "dapr.StateOptions"
    end
    add_message "dapr.SaveStateEnvelope" do
      optional :storeName, :string, 1
      repeated :requests, :message, 2, "dapr.StateRequest"
    end
    add_message "dapr.GetStateEnvelope" do
      optional :storeName, :string, 1
      optional :key, :string, 2
      optional :consistency, :string, 3
    end
    add_message "dapr.GetStateResponseEnvelope" do
      optional :data, :message, 1, "google.protobuf.Any"
      optional :etag, :string, 2
    end
    add_message "dapr.GetSecretEnvelope" do
      optional :storeName, :string, 1
      optional :key, :string, 2
      map :metadata, :string, :string, 3
    end
    add_message "dapr.GetSecretResponseEnvelope" do
      map :data, :string, :string, 1
    end
    add_message "dapr.InvokeBindingEnvelope" do
      optional :name, :string, 1
      optional :data, :message, 2, "google.protobuf.Any"
      map :metadata, :string, :string, 3
    end
    add_message "dapr.InvokeServiceEnvelope" do
      optional :id, :string, 1
      optional :method, :string, 2
      optional :data, :message, 3, "google.protobuf.Any"
      map :metadata, :string, :string, 4
    end
    add_message "dapr.PublishEventEnvelope" do
      optional :topic, :string, 1
      optional :data, :message, 2, "google.protobuf.Any"
    end
    add_message "dapr.State" do
      optional :key, :string, 1
      optional :value, :message, 2, "google.protobuf.Any"
      optional :etag, :string, 3
      map :metadata, :string, :string, 4
      optional :options, :message, 5, "dapr.StateOptions"
    end
    add_message "dapr.StateOptions" do
      optional :concurrency, :string, 1
      optional :consistency, :string, 2
      optional :retryPolicy, :message, 3, "dapr.RetryPolicy"
    end
    add_message "dapr.RetryPolicy" do
      optional :threshold, :int32, 1
      optional :pattern, :string, 2
      optional :interval, :message, 3, "google.protobuf.Duration"
    end
    add_message "dapr.StateRequest" do
      optional :key, :string, 1
      optional :value, :message, 2, "google.protobuf.Any"
      optional :etag, :string, 3
      map :metadata, :string, :string, 4
      optional :options, :message, 5, "dapr.StateRequestOptions"
    end
    add_message "dapr.StateRequestOptions" do
      optional :concurrency, :string, 1
      optional :consistency, :string, 2
      optional :retryPolicy, :message, 3, "dapr.StateRetryPolicy"
    end
    add_message "dapr.StateRetryPolicy" do
      optional :threshold, :int32, 1
      optional :pattern, :string, 2
      optional :interval, :message, 3, "google.protobuf.Duration"
    end
  end
end

module Dapr
  InvokeServiceResponseEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.InvokeServiceResponseEnvelope").msgclass
  DeleteStateEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.DeleteStateEnvelope").msgclass
  SaveStateEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.SaveStateEnvelope").msgclass
  GetStateEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.GetStateEnvelope").msgclass
  GetStateResponseEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.GetStateResponseEnvelope").msgclass
  GetSecretEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.GetSecretEnvelope").msgclass
  GetSecretResponseEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.GetSecretResponseEnvelope").msgclass
  InvokeBindingEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.InvokeBindingEnvelope").msgclass
  InvokeServiceEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.InvokeServiceEnvelope").msgclass
  PublishEventEnvelope = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.PublishEventEnvelope").msgclass
  State = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.State").msgclass
  StateOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.StateOptions").msgclass
  RetryPolicy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.RetryPolicy").msgclass
  StateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.StateRequest").msgclass
  StateRequestOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.StateRequestOptions").msgclass
  StateRetryPolicy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.StateRetryPolicy").msgclass
end
