# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dapr/proto/common/v1/common.proto

require 'google/protobuf'

require 'google/protobuf/any_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("dapr/proto/common/v1/common.proto", :syntax => :proto3) do
    add_message "dapr.proto.common.v1.HTTPExtension" do
      optional :verb, :enum, 1, "dapr.proto.common.v1.HTTPExtension.Verb"
      optional :querystring, :string, 2
    end
    add_enum "dapr.proto.common.v1.HTTPExtension.Verb" do
      value :NONE, 0
      value :GET, 1
      value :HEAD, 2
      value :POST, 3
      value :PUT, 4
      value :DELETE, 5
      value :CONNECT, 6
      value :OPTIONS, 7
      value :TRACE, 8
    end
    add_message "dapr.proto.common.v1.InvokeRequest" do
      optional :method, :string, 1
      optional :data, :message, 2, "google.protobuf.Any"
      optional :content_type, :string, 3
      optional :http_extension, :message, 4, "dapr.proto.common.v1.HTTPExtension"
    end
    add_message "dapr.proto.common.v1.InvokeResponse" do
      optional :data, :message, 1, "google.protobuf.Any"
      optional :content_type, :string, 2
    end
    add_message "dapr.proto.common.v1.StateItem" do
      optional :key, :string, 1
      optional :value, :bytes, 2
      optional :etag, :message, 3, "dapr.proto.common.v1.Etag"
      map :metadata, :string, :string, 4
      optional :options, :message, 5, "dapr.proto.common.v1.StateOptions"
    end
    add_message "dapr.proto.common.v1.Etag" do
      optional :value, :string, 1
    end
    add_message "dapr.proto.common.v1.StateOptions" do
      optional :concurrency, :enum, 1, "dapr.proto.common.v1.StateOptions.StateConcurrency"
      optional :consistency, :enum, 2, "dapr.proto.common.v1.StateOptions.StateConsistency"
    end
    add_enum "dapr.proto.common.v1.StateOptions.StateConcurrency" do
      value :CONCURRENCY_UNSPECIFIED, 0
      value :CONCURRENCY_FIRST_WRITE, 1
      value :CONCURRENCY_LAST_WRITE, 2
    end
    add_enum "dapr.proto.common.v1.StateOptions.StateConsistency" do
      value :CONSISTENCY_UNSPECIFIED, 0
      value :CONSISTENCY_EVENTUAL, 1
      value :CONSISTENCY_STRONG, 2
    end
  end
end

module Dapr
  module Proto
    module Common
      module V1
        HTTPExtension = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.proto.common.v1.HTTPExtension").msgclass
        HTTPExtension::Verb = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.proto.common.v1.HTTPExtension.Verb").enummodule
        InvokeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.proto.common.v1.InvokeRequest").msgclass
        InvokeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.proto.common.v1.InvokeResponse").msgclass
        StateItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.proto.common.v1.StateItem").msgclass
        Etag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.proto.common.v1.Etag").msgclass
        StateOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.proto.common.v1.StateOptions").msgclass
        StateOptions::StateConcurrency = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.proto.common.v1.StateOptions.StateConcurrency").enummodule
        StateOptions::StateConsistency = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("dapr.proto.common.v1.StateOptions.StateConsistency").enummodule
      end
    end
  end
end
