# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: dapr/proto/runtime/v1/appcallback.proto for package 'dapr.proto.runtime.v1'
# Original file comments:
#
# Copyright 2021 The Dapr Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'dapr/proto/runtime/v1/appcallback_pb'

module Dapr
  module Proto
    module Runtime
      module V1
        module AppCallback
          # AppCallback V1 allows user application to interact with Dapr runtime.
          # User application needs to implement AppCallback service if it needs to
          # receive message from dapr runtime.
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'dapr.proto.runtime.v1.AppCallback'

            # Invokes service method with InvokeRequest.
            rpc :OnInvoke, ::Dapr::Proto::Common::V1::InvokeRequest, ::Dapr::Proto::Common::V1::InvokeResponse
            # Lists all topics subscribed by this app.
            rpc :ListTopicSubscriptions, ::Google::Protobuf::Empty, ::Dapr::Proto::Runtime::V1::ListTopicSubscriptionsResponse
            # Subscribes events from Pubsub
            rpc :OnTopicEvent, ::Dapr::Proto::Runtime::V1::TopicEventRequest, ::Dapr::Proto::Runtime::V1::TopicEventResponse
            # Lists all input bindings subscribed by this app.
            rpc :ListInputBindings, ::Google::Protobuf::Empty, ::Dapr::Proto::Runtime::V1::ListInputBindingsResponse
            # Listens events from the input bindings
            #
            # User application can save the states or send the events to the output
            # bindings optionally by returning BindingEventResponse.
            rpc :OnBindingEvent, ::Dapr::Proto::Runtime::V1::BindingEventRequest, ::Dapr::Proto::Runtime::V1::BindingEventResponse
          end

          Stub = Service.rpc_stub_class
        end
        module AppCallbackHealthCheck
          # AppCallbackHealthCheck V1 is an optional extension to AppCallback V1 to implement
          # the HealthCheck method.
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'dapr.proto.runtime.v1.AppCallbackHealthCheck'

            # Health check.
            rpc :HealthCheck, ::Google::Protobuf::Empty, ::Dapr::Proto::Runtime::V1::HealthCheckResponse
          end

          Stub = Service.rpc_stub_class
        end
        module AppCallbackAlpha
          # AppCallbackAlpha V1 is an optional extension to AppCallback V1 to opt
          # for Alpha RPCs.
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'dapr.proto.runtime.v1.AppCallbackAlpha'

            # Subscribes bulk events from Pubsub
            rpc :OnBulkTopicEventAlpha1, ::Dapr::Proto::Runtime::V1::TopicEventBulkRequest, ::Dapr::Proto::Runtime::V1::TopicEventBulkResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
