# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: dapr/proto/runtime/v1/dapr.proto for package 'dapr.proto.runtime.v1'
# Original file comments:
# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------
#

require 'grpc'
require 'dapr/proto/runtime/v1/dapr_pb'

module Dapr
  module Proto
    module Runtime
      module V1
        module Dapr
          # Dapr service provides APIs to user application to access Dapr building blocks.
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'dapr.proto.runtime.v1.Dapr'

            # Invokes a method on a remote Dapr app.
            rpc :InvokeService, InvokeServiceRequest, Dapr::Proto::Common::V1::InvokeResponse
            # Gets the state for a specific key.
            rpc :GetState, GetStateRequest, GetStateResponse
            # Saves the state for a specific key.
            rpc :SaveState, SaveStateRequest, Google::Protobuf::Empty
            # Deletes the state for a specific key.
            rpc :DeleteState, DeleteStateRequest, Google::Protobuf::Empty
            # Publishes events to the specific topic.
            rpc :PublishEvent, PublishEventRequest, Google::Protobuf::Empty
            # Invokes binding data to specific output bindings
            rpc :InvokeBinding, InvokeBindingRequest, InvokeBindingResponse
            # Gets secrets from secret stores.
            rpc :GetSecret, GetSecretRequest, GetSecretResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
